### ISSUE TITLE
Include more Discord user info in job listings

### ISSUE THREAD

**Issue by nickserv** [reactiflux/reactiflux.com#114]
Some users exclude contact information from their post, assuming that they'll get back a DM on Discord. Unfortunately this means that if multiple users have the same display name, it won't be clear which user to contact based on the jobs site alone. We should include some uniquely identifying info (like user id with `#` or the user id integer) so users can be contacted even if they have common display names.

**Comment by aeworxet** [comment]
```
https://reactistory.com:8443/api/job
```
in
```
./src/pages/jobs.js:101:15
```
responds with

```
"author": {
  "name": "melaleuca5", // no '#2695' part
  "id": "127676623435726848"
}
```

I have added to username a Discord link containing `id`
(`https://discordapp.com/users/127676623435726848` in this case) in PR #164,
but concerning addition of the hash part to the username - might this change be
required to be implemented at `reactistory.com` rather than at
`reactiflux.com`?

**Comment by BTMPL** [comment]
Hm, I thnikin showing "normal" username and linking to the user ID should be enough. But if you think it's needed, I believe I can add it to the api (I think it's not stored, so wouldn't be providing it for legacy posts).
