### ISSUE TITLE
Q&A Schedule Minor Issue

### ISSUE THREAD

**Issue by gabegreenberg** [reactiflux/reactiflux.com#9]
@Huvik why are these items jumping to the next line? 
<img width="918" alt="screen shot 2017-01-08 at 02 19 51" src="https://cloud.githubusercontent.com/assets/11687622/21748086/14256d52-d549-11e6-9e6e-d6bc24ea1bdb.png">

**Comment by huv1k** [comment]
It's because of this: 
<img width="809" alt="screen shot 2017-01-08 at 11 32 55" src="https://cloud.githubusercontent.com/assets/5691926/21749077/4acee070-d596-11e6-8784-08224bb7e9e2.png">
So we force text on next line on links page. We can change it but we will have text like this:
<img width="812" alt="screen shot 2017-01-08 at 11 40 46" src="https://cloud.githubusercontent.com/assets/5691926/21749118/5c37c2ea-d597-11e6-93d5-15e50ba33c4e.png">
And then we can change format of links depends on you :)

**Comment by gabegreenberg** [comment]
@Huvik lets leave it how it is for now, thanks!
